### ISSUE TITLE
todo: features to add

### ISSUE THREAD

**Issue by thoriqfarras** [thoriqfarras/library#2]
- [ ] a form of storage (local or cloud)
- [ ] if using cloud, a sign in feature
- [ ] a theme switcher
- [ ] URL to my github when user clicks on the github logo
